# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG and others
# SPDX-License-Identifier: Apache-2.0
spring:
  application:
    name: Arc Agent
  jackson:
    default-property-inclusion: NON_NULL
  main:
    banner-mode: off
    web-application-type: reactive
  reactor:
    context-propagation: auto
  graphql:
    graphiql:
      enabled: true

server:
  port: 8080

lmos:
  router:
    llm:
      provider: ${LLM_PROVIDER:azure_openai}
      api-key: ${LLM_API_KEY:your-api-key}
      base-url: ${LLM_BASE_URL:https://your-subdomain.openai.azure.com}
      model: ${LLM_MODEL_NAME:your-model}
      maxChatHistory: ${LLM_MAX_CHAT_HISTORY:10}
    embedding:
      store:
        host: ${EMBEDDING_STORE_HOST:localhost}
        port: ${EMBEDDING_STORE_PORT:6334}
        collection: arc-supervisor
      ranking:
        maxEmbeddings: ${EMBEDDING_RANKING_MAX_EMBEDDINGS:15}
        minWeight: ${EMBEDDING_RANKING_MIN_WEIGHT:5.0}
        minDistance: ${EMBEDDING_RANKING_MIN_DISTANCE:4.0}
        minMeanScore: ${EMBEDDING_RANKING_MIN_MEAN_SCORE:0.8}
        minRealDistance: ${EMBEDDING_RANKING_MIN_REAL_DISTANCE:0.3}
      model:
        local:
          enabled: ${EMBEDDING_MODEL_LOCAL_ENABLED:true}
          model-path: ${EMBEDDING_MODEL_LOCAL_MODEL_PATH:/path/to/your/local/model.onnx}
          tokenizer-path: ${EMBEDDING_MODEL_LOCAL_TOKENIZER_PATH:/path/to/your/local/tokenizer.json}
        huggingface:
          enabled: ${EMBEDDING_MODEL_HUGGINGFACE_ENABLED:false}
          model-name: ${EMBEDDING_MODEL_HUGGINGFACE_MODEL_NAME:mixedbread-ai/deepset-mxbai-embed-de-large-v1}
          api-key: ${EMBEDDING_MODEL_HUGGINGFACE_API_KEY:your-api-key}

arc:
  ai:
    clients:
      - id: GPT-4o
        client: openai
        model-name: ${LLM_MODEL_NAME:your-model}
        api-key: ${LLM_API_KEY:my-api-key}
      - id: llama3.2
        client: ollama
        modelName: llama3.2
      - id: GPT-4o-Azure
        model-name: ${LLM_MODEL_NAME:your-model}
        api-key: ${LLM_API_KEY:your-api-key}
        client: azure
        url: ${LLM_BASE_URL:https://your-subdomain.openai.azure.com}
  cors:
    enabled: true
  scripts:
    enabled: true
    folder: agents
    hotReload:
      enable: true
      delay: PT1S
  chat:
    ui:
      enabled: true
  subscriptions:
    events:
      enable: true

logging:
  level:
    root: INFO
    io.grpc: INFO
    org.eclipse.lmos.arc: WARN
    org.eclipse.lmos.arc.app: WARN
    ArcDSL: WARN

management:
  tracing:
    enabled: false
    sampling:
      probability: 1.0
  server:
    port: 9090
  endpoints:
    web:
      base-path: /
      exposure:
        include: prometheus,metrics,info,health
  endpoint:
    metrics:
      enabled: true
    health:
      probes:
        enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
