services:
  lmos-router-poc:
    image: ghcr.io/sbussweiler/lmos-router-poc:0.1.0-SNAPSHOT
    container_name: lmos-router-poc
    pull_policy: always
    environment:
      # Increase the direct memory size, otherwise the embedding creation will end up with OOM
      JAVA_TOOL_OPTIONS: "-XX:MaxDirectMemorySize=1G"
      # Embedding Store settings
      EMBEDDING_STORE_HOST: "qdrant"
      EMBEDDING_STORE_PORT: "6334"
      # Embedding Ranking settings
      EMBEDDING_RANKING_MAX_EMBEDDINGS: "${EMBEDDING_RANKING_MAX_EMBEDDINGS}"
      EMBEDDING_RANKING_MIN_WEIGHT: "${EMBEDDING_RANKING_MIN_WEIGHT}"
      EMBEDDING_RANKING_MIN_DISTANCE: "${EMBEDDING_RANKING_MIN_DISTANCE}"
      EMBEDDING_RANKING_MIN_MEAN_SCORE: "${EMBEDDING_RANKING_MIN_MEAN_SCORE}"
      EMBEDDING_RANKING_MIN_REAL_DISTANCE: "${EMBEDDING_RANKING_MIN_REAL_DISTANCE}"
      # Embedding Model settings
      EMBEDDING_MODEL_DOCUMENT_PATH: "/app/documents"
      EMBEDDING_MODEL_LOCAL_ENABLED: "${EMBEDDING_MODEL_LOCAL_ENABLED}"
      EMBEDDING_MODEL_LOCAL_MODEL_PATH: "/app/model/${EMBEDDING_MODEL_LOCAL_FILE_NAME}"
      EMBEDDING_MODEL_LOCAL_TOKENIZER_PATH: "/app/model/${EMBEDDING_MODEL_LOCAL_TOKENIZER_FILE_NAME}"
      EMBEDDING_MODEL_HUGGINGFACE_ENABLED: "${EMBEDDING_MODEL_HUGGINGFACE_ENABLED}"
      EMBEDDING_MODEL_HUGGINGFACE_MODEL_NAME: "${EMBEDDING_MODEL_HUGGINGFACE_MODEL_NAME}"
      EMBEDDING_MODEL_HUGGINGFACE_API_KEY: "${EMBEDDING_MODEL_HUGGINGFACE_API_KEY}"
      # Azure LLM settings
      LLM_PROVIDER: "${LLM_PROVIDER}"
      LLM_API_KEY: "${LLM_API_KEY}"
      LLM_BASE_URL: "${LLM_BASE_URL}"
      LLM_MODEL_NAME: "${LLM_MODEL_NAME}"
      # LLM History settings
      LLM_MAX_CHAT_HISTORY: "${LLM_MAX_CHAT_HISTORY}"
      LLM_SYSTEM_PROMPT: >
        Die folgenden Agenten stehen zur Bearbeitung der weiter unten genannten Kundenkonversation zur Verfügung:
        {{agents}}

        Bitte wähle den richtigen Agenten für den Kunden aus und liefere die agentId zurück.
        Beispielantwort:
        {
            "agentId": "<given-agent-id>"
        }

        Wenn kein geeigneter Agent ausgewählt werden kann, gebe 'null' als Agenten-ID zurück.
        Beispielantwort:
        {
            "agentId": null
        }
    volumes:
      - "${CAPABILITIES_DOCUMENTS_DIR}:/app/documents"
      - "${EMBEDDING_MODEL_LOCAL_DIR}:/app/model"
      - "~/.azure:/home/router/.azure"
    ports:
      - "8080:8080"
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant-container
    ports:
      - "6333:6333"
      - "6334:6334"
    environment:
      - QDRANT__SERVICE__WORKERS=2
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__SERVICE__HTTP_PORT=6333
    volumes:
      - ./qdrant-storage:/qdrant/storage
